### ISSUE TITLE
Problem with active/inactive date (from example 2)

### ISSUE THREAD

**Issue by vcurdia** [rougier/svg-tag-mode#56]
I tried to use example 2 to fontify date/times in scheduled/deadline items but I get error messages on loading the configuration.

Happens on Emacs 29.1 in both Windows 10 and Ubuntu 22.04.

My (shortened) setup:
```lisp
;; use svg-tag-mode
(defconst date-re "[0-9]\\{4\\}-[0-9]\\{2\\}-[0-9]\\{2\\}")
(defconst time-re "[0-9]\\{2\\}:[0-9]\\{2\\}")
(defconst day-re "[A-Za-z]\\{3\\}")
(defconst day-time-re (format "\\(%s\\)? ?\\(%s\\)?" day-re time-re))
(use-package svg-tag-mode
  :config
  (setq svg-tag-tags
      '(
        ;; Task priority
        ("\\[#[A-Z]\\]" . ( (lambda (tag)
                              (svg-tag-make tag :face 'org-priority 
                                            :beg 2 :end -1 :margin 0
					    :height 0.58 :radius 5))))
	
        ;; Active date (with or without day name, with or without time)
        (,(format "\\(<%s>\\)" date-re) .
         ((lambda (tag)
            (svg-tag-make tag :beg 1 :end -1 :margin 0))))
        (,(format "\\(<%s \\)%s>" date-re day-time-re) .
         ((lambda (tag)
            (svg-tag-make tag :beg 1 :inverse nil :crop-right t :margin 0))))
        (,(format "<%s \\(%s>\\)" date-re day-time-re) .
         ((lambda (tag)
            (svg-tag-make tag :end -1 :inverse t :crop-left t :margin 0))))

        ;; Inactive date  (with or without day name, with or without time)
         (,(format "\\(\\[%s\\]\\)" date-re) .
          ((lambda (tag)
             (svg-tag-make tag :beg 1 :end -1 :margin 0 :face 'org-date))))
         (,(format "\\(\\[%s \\)%s\\]" date-re day-time-re) .
         ((lambda (tag)
             (svg-tag-make tag :beg 1 :inverse nil :crop-right t :margin 0 :face 'org-date))))
         (,(format "\\[%s \\(%s\\]\\)" date-re day-time-re) .
          ((lambda (tag)
             (svg-tag-make tag :end -1 :inverse t :crop-left t :margin 0 :face 'org-date))))

	 ))
  ;; fix agenda view
  (defun org-agenda-show-svg ()
    (let* ((case-fold-search nil)
           (keywords (mapcar #'svg-tag--build-keywords svg-tag--active-tags))
           (keyword (car keywords)))
      (while keyword
        (save-excursion
          (while (re-search-forward (nth 0 keyword) nil t)
            (overlay-put (make-overlay
                          (match-beginning 0) (match-end 0))
                         'display  (nth 3 (eval (nth 2 keyword)))) ))
        (pop keywords)
        (setq keyword (car keywords)))))
  (add-hook 'org-agenda-finalize-hook #'org-agenda-show-svg)
  )
(global-svg-tag-mode t)
```
On initializing Emacs I get the following error message:
`Wrong type argument: stringp, (, (format \(<%s>\) date-re))`

Any idea what is the issue?

**Comment by rougier** [comment]
Can you switch toggle-debug-on-error such that we have a more detailed report?

**Comment by vcurdia** [comment]
This is what I got after turning on debug on error:
`Debugger entered--Lisp error: (wrong-type-argument stringp ,(format "\\(<%s>\\)" date-re))
  svg-tag--build-keywords((,(format "\\(<%s>\\)" date-re) (lambda (tag) (svg-tag-make tag :beg 1 :end -1 :margin 0))))
  svg-tag-mode-on()
  global-svg-tag-mode-enable-in-buffers()
  run-hooks(after-change-major-mode-hook)
  run-mode-hooks(special-mode-hook)
  special-mode()
  eldoc--format-doc-buffer((("Embark on identifier ‘your’")))
  eldoc-display-in-echo-area((("Embark on identifier ‘your’")) nil)
  run-hook-with-args(eldoc-display-in-echo-area (("Embark on identifier ‘your’")) nil)
  #f(compiled-function () #<bytecode 0x13f438dd9c27256>)()
  #f(compiled-function (string &rest plist) #<bytecode 0x138508dae21649a6>)("Embark on identifier ‘your’")
  embark-eldoc-first-target(#f(compiled-function (string &rest plist) #<bytecode 0x138508dae21649a6>))
  eldoc-documentation-default()
  eldoc--invoke-strategy(nil)
  eldoc-print-current-symbol-info()
  #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_13>()
  apply(#<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_13> nil)
  timer-event-handler([t 0 0 500000 nil #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_13> nil idle 0 nil])
`

**Comment by rougier** [comment]
Can you try latest github version and run example-2.el (eval buffer). I pushed different fixes that might solve your problem.

**Comment by vcurdia** [comment]
It works now.

Note that even after updating your package (using melpa) I was still having the same error message until I realized that in the command '(setq svg-tag-tags `(<...>))' I was using a list defined as
```
...
'(
...
```
instead of 
```
...
`(
...
```
